version: "3.7"
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "39121:80"
    healthcheck:
      test: curl -f http://localhost
      interval: 10s
      timeout: 3s
    restart: always

networks:
  default:
    external:
      name: testing-env 
